[build-system]
build-backend = "hatchling.build"
requires = ["hatchling<1.22"]

[project]
requires-python = ">=3.10"
name = "chainable"
version = "1.0"

[tool.hatch.build.targets.wheel]
packages = ["chainable"]
